### ISSUE TITLE
crash when episode is not found

### ISSUE THREAD

**Issue by sirber** [scarpentier/toutv-extra#12]
# toutv fetch -m unite-9/S04E17

Executing fetch (Download a media):
    MediaUrl : unite-9/S04E17 

Unhandled Exception: Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path '', line 1, position 4.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at toutv.Fetch.Run(String[] remainingArguments)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at toutv.Program.Main(String[] args)

**Comment by sirber** [comment]
C:\Users\sirber\Desktop\toutv-extra-master>toutv.exe fetch -m unite-9/S05E11

Executing fetch (Download a media):
    MediaUrl : unite-9/S05E11


Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\sirber\Desktop\toutv-extra-master\token.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at toutv.Fetch.Run(String[] remainingArguments)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at toutv.Program.Main(String[] args)

**Comment by scarpentier** [comment]
The token file cannot be found in the program directory. Most likely you didn't login before using the `fetch` command, or you're using a different "startup path" than when you did login.
